### ISSUE TITLE
Doesn't work, throws a Syntax Error

### ISSUE THREAD

**Issue by garyking** [typeorm/electron-typescript-example#2]
If I run this, I get:

```
App threw an error during load
electron-typescript-example/node_modules/cli-highlight/node_modules/chalk/source/index.js:103
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (electron-typescript-example/node_modules/cli-highlight/dist/theme.js:10:28)
```

**Comment by Sinmson** [comment]
Same for me

**Comment by axeprpr** [comment]
Same for me...this example need to be updated.

**Comment by Ngomana** [comment]
has anyone found a solution?
