### ISSUE TITLE
Example how to use TypeORM with Electron using TypeScript

### ISSUE THREAD

**Issue by HimorriveL** [typeorm/electron-typescript-example#4]
Hello guys, TypeORM is no more working with Electron?

I clone this link https://github.com/typeorm/electron-typescript-example

and run for download dependencias and when I start i got this error:

`App threw an error during load C:\Users\Acer\Desktop\once\electron-typescript-example\node_modules\typeorm\node_modules\chalk\source\index.js:106
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Acer\Desktop\once\electron-typescript-example\node_modules\typeorm\platform\PlatformTools.js:7:39)
`

**Comment by siddrcrelias** [comment]
still facing this here :(
